# Generated by Django 5.2.2 on 2025-06-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FitnessClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dtm", models.DateTimeField(auto_now_add=True)),
                ("updated_dtm", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("datetime", models.DateTimeField()),
                ("instructor", models.CharField(max_length=100)),
                ("total_slots", models.PositiveIntegerField()),
                ("available_slots", models.PositiveIntegerField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
            ],
            options={
                "verbose_name": "Fitness Class",
                "db_table": "fitness_class",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_dtm", models.DateTimeField(auto_now_add=True)),
                ("updated_dtm", models.DateTimeField(auto_now=True)),
                ("client_name", models.CharField(max_length=100)),
                ("client_email", models.EmailField(max_length=254)),
                ("booking_time", models.DateTimeField(auto_now_add=True)),
                ("is_cancelled", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fitness_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.fitnessclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "db_table": "booking",
            },
        ),
    ]
